-- ============================================================
-- LAB DATABASE
-- Migration: V1
-- Description: Initial schema
-- Database: Oracle
-- ============================================================


-- ============================================================
-- 0. DROP EXISTING TABLES
-- ============================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_CRAWLED_RECORD CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_CHANNEL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_USER_DOMAIN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_DOMAIN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_USER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- ============================================================
-- 1. LAB_USER
-- ============================================================

CREATE TABLE LAB_USER (
                          ID VARCHAR2(25)
                              CONSTRAINT PK_LAB_USER
                                  PRIMARY KEY,

                          USERNAME VARCHAR2(100)
                              CONSTRAINT UK_LAB_USER_USERNAME
                                  UNIQUE
                              NOT NULL,

                          EMAIL VARCHAR2(255)
                              CONSTRAINT UK_LAB_USER_EMAIL
                                  UNIQUE
                              NOT NULL,

                          PASSWORD_HASH VARCHAR2(255)
                              NOT NULL,

                          FULL_NAME VARCHAR2(255),

                          ROLE VARCHAR2(20)
                              NOT NULL,

                          STATUS VARCHAR2(20)
                              NOT NULL,

                          CREATED_AT TIMESTAMP
                              DEFAULT SYSTIMESTAMP
                              NOT NULL,

                          UPDATED_AT TIMESTAMP
                              DEFAULT SYSTIMESTAMP
                              NOT NULL,

                          CONSTRAINT CK_LAB_USER_ROLE
                              CHECK (ROLE IN ('USER', 'ADMIN')),

                          CONSTRAINT CK_LAB_USER_STATUS
                              CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);


-- ============================================================
-- 2. LAB_DOMAIN
-- ============================================================

CREATE TABLE LAB_DOMAIN (
                            ID NUMBER(19)
                                GENERATED BY DEFAULT AS IDENTITY
                                CONSTRAINT PK_LAB_DOMAIN
                                    PRIMARY KEY,

                            CODE VARCHAR2(50)
                                CONSTRAINT UK_LAB_DOMAIN_CODE
                                    UNIQUE
                                NOT NULL,

                            NAME VARCHAR2(255)
                                NOT NULL,

                            STATUS VARCHAR2(20)
                                NOT NULL,

                            CREATED_AT TIMESTAMP
                                DEFAULT SYSTIMESTAMP
                                NOT NULL,

                            CREATED_BY VARCHAR2(25)
                                NOT NULL,

                            UPDATED_AT TIMESTAMP,

                            UPDATED_BY VARCHAR2(25),

                            CONSTRAINT CK_LAB_DOMAIN_STATUS
                                CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);


-- ============================================================
-- 3. LAB_USER_DOMAIN
-- ============================================================

CREATE TABLE LAB_USER_DOMAIN (
                                 ID NUMBER(19)
                                     GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT PK_LAB_USER_DOMAIN
                                         PRIMARY KEY,

                                 USER_ID VARCHAR2(25)
                                     NOT NULL,

                                 DOMAIN_ID NUMBER(19)
                                     NOT NULL,

                                 ASSIGNED_AT TIMESTAMP
                                     DEFAULT SYSTIMESTAMP
                                     NOT NULL,

                                 ASSIGNED_BY VARCHAR2(25)
                                     NOT NULL,

                                 REVOKED_AT TIMESTAMP,

                                 REVOKED_BY VARCHAR2(25)
);


-- ============================================================
-- 4. LAB_CHANNEL
-- ============================================================

CREATE TABLE LAB_CHANNEL (
                             ID NUMBER(19)
                                 GENERATED BY DEFAULT AS IDENTITY
                                 CONSTRAINT PK_LAB_CHANNEL
                                     PRIMARY KEY,

                             DOMAIN_ID NUMBER(19)
                                 NOT NULL,

                             NAME VARCHAR2(255)
                                 NOT NULL,

                             PLATFORM_TYPE VARCHAR2(50)
                                 NOT NULL,

                             STATUS VARCHAR2(20)
                                 NOT NULL,

                             SOURCE_URL VARCHAR2(1000),

                             CONFIG CLOB,

                             CREATED_AT TIMESTAMP
                                 DEFAULT SYSTIMESTAMP
                                 NOT NULL,

                             CREATED_BY VARCHAR2(25)
                                 NOT NULL,

                             UPDATED_AT TIMESTAMP,

                             UPDATED_BY VARCHAR2(25),

                             CONSTRAINT CK_LAB_CHANNEL_STATUS
                                 CHECK (STATUS IN ('DRAFT', 'RUNNING', 'STOPPED'))
);


-- ============================================================
-- 5. LAB_CRAWLED_RECORD
-- ============================================================

CREATE TABLE LAB_CRAWLED_RECORD (
                                    ID NUMBER(19)
                                        GENERATED BY DEFAULT AS IDENTITY
                                        CONSTRAINT PK_LAB_CRAWLED_RECORD
                                            PRIMARY KEY,

                                    CHANNEL_ID NUMBER(19)
                                        NOT NULL,

                                    TITLE VARCHAR2(500),

                                    CONTENT CLOB,

                                    PUBLISHED_AT TIMESTAMP,

                                    CRAWLED_AT TIMESTAMP
                                        DEFAULT SYSTIMESTAMP
                                        NOT NULL,

                                    PROCESSING_STATUS VARCHAR2(20)
                                        NOT NULL,

                                    ERROR_MESSAGE VARCHAR2(1000),

                                    CREATED_AT TIMESTAMP
                                        DEFAULT SYSTIMESTAMP
                                        NOT NULL,

                                    CONSTRAINT CK_LAB_CRAWLED_RECORD_STATUS
                                        CHECK (
                                            PROCESSING_STATUS IN (
                                                                  'NEW',
                                                                  'PROCESSED',
                                                                  'ERROR'
                                                )
                                            )
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IDX_LAB_USER_DOMAIN_USER
    ON LAB_USER_DOMAIN (USER_ID);

CREATE INDEX IDX_LAB_USER_DOMAIN_DOMAIN
    ON LAB_USER_DOMAIN (DOMAIN_ID);

CREATE INDEX IDX_LAB_CHANNEL_DOMAIN
    ON LAB_CHANNEL (DOMAIN_ID);

CREATE INDEX IDX_LAB_CRAWLED_RECORD_CHANNEL
    ON LAB_CRAWLED_RECORD (CHANNEL_ID);

CREATE INDEX IDX_LAB_CRAWLED_RECORD_STATUS
    ON LAB_CRAWLED_RECORD (PROCESSING_STATUS);